language: node_js
node:
- '12'
install:
- make build
script:
- make plan
deploy:
- provider: script
  script: make apply
  skip_cleanup: true
  on:
    repo: techworkersco/twc-site-boston
    tags: true
