version: '3'
services:
  npm:
    entrypoint: npm
    image: lambci/lambda:build-nodejs8.10
    volumes:
    - ./:/var/task
  build:
    command: >-
      sh -c "
        mkdir -p build &&
        cp -r app.js lambda.js package.json package-lock.json views build/ &&
        cd build &&
        npm install --production
      "
    image: lambci/lambda:build-nodejs8.10
    volumes:
    - ./:/var/task
