version: '3'
services:
  lambda:
    command: >
      sh -c "
        npm install &&
        zip -r package.zip node_modules/ app.js index.html lambda.js package.json package-lock.json &&
        mv package.zip /dist/package.zip
        aws s3 cp /dist/package.zip s3://${S3_BUCKET}/${S3_KEY}
      "
    env_file: ./.env
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - ./src:/var/task
      - ./dist:/dist
