version: '3'
services:

  build:
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - layer:/opt/nodejs
      - ./:/var/task

  dist:
    command: zip -r - .
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - layer:/opt/nodejs
    working_dir: /opt

  test:
    command: lambda.handler '{"path":"/"}'
    env_file: .env
    image: lambci/lambda:nodejs8.10
    volumes:
      - ./:/var/task
      - layer:/opt/nodejs

volumes:
  layer:
